version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usersdb
    ports: ["3306:3306"]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  solr:
    image: solr:9
    command: ["solr-precreate", "courts"]
    ports: ["8983:8983"]

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672","15672:15672"]

  memcached:
    image: memcached:1.6
    ports: ["11211:11211"]

  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    env_file:
      - ./users-api/.env.example
    depends_on:
      mysql:
        condition: service_healthy
    ports: ["8081:8080"]

  canchas-api:
    build:
      context: ./canchas-api
      dockerfile: Dockerfile
    env_file:
      - ./canchas-api/.env.example
    depends_on:
      - mongo
      - rabbitmq
    ports: ["8082:8080"]

  reservas-api:
    build:
      context: ./reservas-api
      dockerfile: Dockerfile
    env_file:
      - ./reservas-api/.env.example
    depends_on:
      - mongo
      - rabbitmq
      - users-api
    ports: ["8083:8080"]

  search-api:
    build:
      context: ./search-api
      dockerfile: Dockerfile
    env_file:
      - ./search-api/.env.example
    depends_on:
      - solr
      - rabbitmq
      - memcached
    ports: ["8084:8080"]

volumes:
  mysql_data: {}
  mongo_data: {}
